select *, 2008 as year from Nomis.dbo.tblPlan_2008  
INNER JOIN (SELECT mIN(gl) AS gl,MIN(CATID) AS CATID ,RPTDESC,MIN(dESCRIPTION) AS dESCRIPTION,MIN(HELP) AS HELP ,MIN(RPTCAT) AS RPTCAT,MIN(RPTID) AS RPTID FROM [LCL-FAXS].LCLADMIN_BAK.dbo.TBLGL GROUP BY RPTDESC) AS b on category = rptdesc

SELECT * FROM  Nomis.dbo.tblPlan_2008

SELECT mIN(gl) AS gl,MIN(CATID) AS CATID ,RPTDESC,MIN(dESCRIPTION) AS dESCRIPTION,MIN(HELP) AS HELP ,MIN(RPTCAT) AS RPTCAT,MIN(RPTID) AS RPTID FROM [LCL-FAXS].LCLADMIN_BAK.dbo.TBLGL GROUP BY RPTDESC

SELECT RPTDESC,COUNT(*) FROM [LCL-FAXS].LCLADMIN_BAK.dbo.TBLGL GROUP BY RPTDESC
SELECT * FROM [LCL-FAXS].LCLADMIN_BAK.dbo.TBLGL